import { z } from "zod";

export const intakeSchema = z.object({
  registrationDate: z.string().min(1, "Required"),
  fullName: z.string().min(2, "Required").max(120),
  dateOfBirth: z.string().min(1, "Required"),
  address: z.string().min(5, "Required").max(300),
  phoneNumber: z.string().min(7, "Required").max(40),
  email: z.string().email("Invalid email").max(200),
  employmentStatus: z.string().min(1, "Required").max(100),
  employer: z.string().max(120).optional(),
  takingMedications: z.enum(["yes", "no"]),
  medicationsList: z.string().max(1000).optional(),
  emergencyContact: z.string().min(2, "Required").max(300),
  height: z.string().min(1, "Required").max(40),
  weight: z.string().min(1, "Required").max(40),
  drinksAlcohol: z.enum(["yes", "no"]),
  smokesCigarettes: z.enum(["yes", "no"]),
  recreationalDrugs: z.enum(["yes", "no"]),
  preExistingConditions: z.enum(["yes", "no"]),
  preExistingConditionsDetails: z.string().max(1000).optional(),
  diagnosedDiabetes: z.enum(["yes", "no"]),
  diagnosedThyroid: z.enum(["yes", "no"]),
  diagnosedPancreatitis: z.enum(["yes", "no"]),
  medicalConditionsDetails: z.string().max(1000).optional(),
  familyHistoryIllness: z.enum(["yes", "no"]),
  familyHistoryDetails: z.string().max(1000).optional(),
  currentlyPregnant: z.enum(["yes", "no"]),
  tryingToConceive: z.enum(["yes", "no"]),
  currentlyBreastfeeding: z.enum(["yes", "no"]),
  lastBloodLabWork: z.string().min(1, "Required").max(100),
  lastBloodPressureDate: z.string().min(1, "Required").max(100),
  lastBloodPressureResults: z.string().min(1, "Required").max(200),
  covidVaccinationStatus: z.enum(["one_dose", "two_doses", "three_doses", "unvaccinated"]),
  underPhysicianSupervision: z.enum(["yes", "no"]),
  reasonForVisit: z.string().min(5, "Please describe your reason for visiting").max(2000),
  servicesInterested: z.array(z.string()).min(1, "Please select at least one service"),
  howDidYouHear: z.enum(["google", "instagram", "facebook", "whatsapp", "snapchat", "referral", "walk_in"]),
  signature: z.string().min(2, "Required").max(120),
});

export type IntakeFormData = z.infer<typeof intakeSchema>;
